name: Release Web

on:
  workflow_dispatch:
  release:
    types: [created]
    paths:
      - "client/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./client

    steps:
      - uses: actions/checkout@v2

      - name: Install modules
        run: pnpm i

      - name: build web
        run: yarn predeploy
        env:
          GRAPHQL_URL: ${{ secrets.GRAPHQL_URL }}
          ROOT_URL: ${{ secrets.ROOT_URL }}
          SUBSCRIPTION_URL: ${{ secrets.SUBSCRIPTION_URL}}
          facebookAppId: ${{ secrets.facebookAppId }}
          facebookSecret: ${{ secrets.facebookSecret }}
          googleWebClientId: ${{ secrets.googleWebClientId }}
          googleAndroidClientId: ${{ secrets.googleAndroidClientId }}
          googleIOSClientId: ${{ secrets.googleIOSClientId }}
          googleSecret: ${{ secrets.googleSecret }}

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_PATH: ./client
